# -*- coding: utf-8 -*-
"""deepen_content.py — extra FAQ Q&As that fill each guide's keyword-cluster gaps.

Each entry targets a specific uncovered keyword from seo/keyword_map.csv (bracketed
notes name the keywords each answer covers). Consumed by deepen_guides.py, which
injects them into the guide's "People also ask" section and its FAQPage JSON-LD.
Answers are written to be genuinely useful, not keyword filler: one real question,
a two-to-three sentence answer, India-specific, occasional internal link.
"""

DEEPEN = {
 "guides/best-music-distributor-india/index.html": [
  ("Is DistroKid available in India, and how much does it cost?",
   "Yes, DistroKid works in India. It charges a flat yearly fee (roughly 1,500 to 2,000 rupees for the base plan) and lets you upload unlimited songs while keeping 100% of your royalties, which makes it cheap if you release often."),
  ("DistroKid vs CD Baby: which is better for Indian artists?",
   "DistroKid charges a yearly fee and takes no cut, best if you release frequently. CD Baby India charges a one-time fee per release but takes a small commission, better if you release rarely and want a permanent listing. For most active independent artists the flat-fee model wins."),
  ("What is the cheapest music distributor in India, and the best for a beginner?",
   'The cheapest routes are free-tier distributors that take a small revenue share instead of an upfront fee. For a beginner who wants no upfront cost and simple setup, a free tier is the easiest start, see our <a href="/guides/free-music-distribution-india/">free distribution guide</a>.'),
  ("Which digital music distribution companies work in India?",
   "The main options for Indian artists are DistroKid, CD Baby, TuneCore, Amuse, RouteNote, and a few India-focused services. All push your music to Spotify, Apple Music, JioSaavn, and YouTube Music; they differ mainly on fee model and extras like caller-tune delivery."),
  ("How long does Spotify take to approve music after I distribute it?",
   "Once your distributor delivers the track, Spotify usually processes it in two to five days, though it can take up to a week or two around busy release periods. Deliver at least four weeks early so you can also pitch it for editorial playlists."),
  ("How do I distribute a full album in India?",
   "The process is the same as a single: upload the tracks, cover art, and metadata to your distributor, set one release date, and it goes live as an album across platforms. Number the tracks correctly and keep the metadata consistent so they group as one release."),
  ("What does Reddit recommend for music distribution in India?",
   "Threads on music subreddits generally favour flat-fee distributors like DistroKid for frequent releasers and warn against services that lock your rights or take large cuts. Treat Reddit as a sentiment check, then verify the fees and terms yourself before choosing."),
 ],
 "guides/submit-music-spotify-playlists-india/index.html": [
  ("How do I submit my music to Spotify playlists in India?",
   'The one official route is Spotify for Artists: pitch an unreleased track at least seven days before release and it reaches the editorial team and improves your Release Radar odds. Beyond that, pitch independent curators directly using our <a href="/reviewers/">curator database</a>.'),
  ("How do I get playlisted on Spotify without followers?",
   "Editorial pitching through Spotify for Artists needs no followers, it is judged on the song and your metadata. For user playlists, target small niche curators who care about the music rather than your numbers."),
  ("Are playlist pitching or promotion services in India worth it?",
   "Legitimate pitching services forward your track to real curators for consideration, they cannot guarantee a placement. Avoid anyone promising a fixed number of streams or guaranteed playlist adds, those rely on bot playlists that can get your track flagged."),
  ("How do I grow monthly listeners and increase Spotify streams in India organically?",
   "Organic growth comes from saves and playlist adds, so pitch every release, put music out on a steady rhythm, and drive fans to save your tracks. Real playlist placements and consistent output lift monthly listeners far more safely than paid streams."),
  ("Is there a playlist pitching email template I can use?",
   "Keep it short: who you are in one line, the track and its vibe, a private link, and why it fits that specific playlist. Curators skim, so lead with the song and the fit, not your bio."),
  ("What are the best Spotify playlist submission sites?",
   'SubmitHub and Groover are the widely used submission platforms, plus Spotify for Artists for editorial. Our <a href="/reviewers/">reviewer database</a> also lists curators who take direct submissions for free.'),
 ],
 "guides/how-to-release-a-song-in-india/index.html": [
  ("How do I release a single independently in India?",
   "Finish and master the track, prepare square art and clean metadata, then upload to a distributor with a release date three to four weeks out so you can pitch playlists. No label or permission is needed to put music out independently."),
  ("What are the steps to release a song?",
   "Master the audio, create 3000x3000 cover art, write accurate metadata (title, artists, songwriters, ISRC), pick a distributor, set the date, then pitch and promote before release day."),
  ("How far in advance should I release music?",
   "Deliver to your distributor at least three to four weeks before the date. Spotify editorial pitching needs seven or more days, and press and playlists want lead time, so earlier is always safer."),
  ("What is a Spotify Canvas and how do I add one?",
   "Canvas is the short looping visual behind your song in the Spotify app. Add it in Spotify for Artists by uploading a three to eight second vertical clip to the track; it tends to lift saves and shares."),
  ("What is music metadata, and what is a one sheet?",
   "Metadata is the text attached to your release, track title, artist names, songwriter credits, ISRC, genre, that platforms and royalty systems read. A one sheet is a single-page summary of the release (art, links, story, key facts) you send to press and curators."),
 ],
 "guides/register-music-copyright-iprs-india/index.html": [
  ("How do I register a song copyright online in India?",
   "You protect the composition by registering with a copyright society, IPRS for music and lyrics, and optionally with the government Copyright Office online. Your recording is separately identified by its ISRC through your distributor."),
  ("How do I release a cover song legally in India?",
   "A cover needs a licence for the underlying composition. In India this usually means a statutory or mechanical licence, or permission via the publisher or IPRS, and some cover-licensing services can handle it. Never release a cover without clearing the composition rights."),
  ("What is music licensing in India?",
   "Music licensing is granting or obtaining permission to use a composition or recording, for a cover, a film, an ad, or a venue. The recording rights and the composition or publishing rights are licensed separately."),
  ("What is the difference between ISRC and ISWC?",
   "An ISRC identifies a specific recording; an ISWC identifies the underlying composition, the song itself across all recordings of it. You get an ISRC from your distributor and an ISWC through your publishing or IPRS registration."),
  ("How do I collect international royalties from India?",
   "Register your compositions with IPRS, which has reciprocal deals with foreign societies, and use publishing administration to collect global publishing royalties; your distributor collects the recording royalties worldwide."),
 ],
 "guides/spotify-pay-per-stream-india/index.html": [
  ("How are music royalties in India explained simply?",
   "Streaming pays two kinds: recording royalties, to whoever owns the master (usually you, via your distributor), and publishing royalties, to the songwriter, collected via IPRS. Both are per-stream and tiny individually."),
  ("How much is 1 million streams worth in India, and what do 1000 streams pay?",
   'At rough Indian per-stream rates, 1,000 streams pays only a few hundred rupees and a million streams lands in the low lakhs, and it depends heavily on listener geography. Use our <a href="/tools/royalty-calculator/">royalty calculator</a> for your own mix.'),
  ("What are mechanical, performance, and neighbouring rights royalties in India?",
   "Mechanical royalties are for reproducing a composition (streams, downloads); performance royalties are for public performance and broadcast; neighbouring rights are for public use of the recording. IPRS and PPL India administer these."),
 ],
 "guides/pitch-music-blogs-press-india/index.html": [
  ("How do I submit music to blogs in India?",
   'Find blogs that cover your genre, use their submission form or a direct editorial email, and send a short pitch with a private link two to three weeks before release. Our <a href="/reviewers/">reviewer database</a> lists Indian blogs and their submission routes.'),
  ("Do I need a music PR agency or publicist in India?",
   "A PR agency or publicist buys relationships and time, useful for a big campaign, but early on you can pitch press yourself. Pay for PR only when you have a genuinely newsworthy release and the budget to match."),
  ("How do I get featured on Rolling Stone India or Wild City?",
   "Pitch a specific editor with a clear news hook, a release, a milestone, a story, not a generic request to be covered. Lead time and an angle that fits their audience matter more than follower count."),
  ("How do I pitch journalists and build a media list for music?",
   "Build a list of writers who actually cover your genre and city, note what each has written, and pitch each one a tailored angle. A small, well-researched media list beats a mass blast."),
 ],
 "guides/book-live-gigs-independent-band-india/index.html": [
  ("How do I get booked for gigs and start performing live in India?",
   "Start with open mics and small venue slots, build a tight 30 to 40 minute set and a short live video, then approach venue bookers and curators with it. A reliable draw is what gets you re-booked."),
  ("Do I need a booking agent in India?",
   "Not early on. Booking agents take a cut and want acts that already draw a crowd; until then you book yourself. An agent makes sense once demand outpaces your time."),
  ("How do I price a gig and get paid in India?",
   "Gig pay ranges widely, from a door split or a few thousand rupees at small venues to much more for corporate and college shows. Agree the fee and terms in writing before the date, and invoice promptly."),
  ("How do I get corporate gigs and college fest gigs in India?",
   'College fests book through student committees in the fest season from December to March; corporate gigs come via event managers and agencies. Both want a clean press kit and video, see our <a href="/guides/electronic-press-kit-epk-india/">EPK guide</a>.'),
  ("How do I organise my own gig or a house concert in India?",
   "Book a small venue or run a living-room house concert, sell tickets directly to your close fans, and keep costs low. Self-organised shows build a real live following that you control."),
 ],
 "guides/music-platforms-independent-artists-india/index.html": [
  ("What are the best platforms to release music on in India?",
   "Spotify, Apple Music, JioSaavn, YouTube Music, and Amazon Music are the core streaming platforms; Bandcamp and SoundCloud add direct-to-fan and community. Your distributor delivers to all of them at once."),
  ("How do I verify my Spotify artist profile and get the verified badge in India?",
   "Claim your profile in Spotify for Artists, usually via the link from your distributor; the blue verified check is granted once you claim it and have at least one live release. It is free."),
  ("Should I use Bandcamp and SoundCloud as an Indian artist?",
   "Bandcamp is strong for selling music and merch directly to fans; SoundCloud for Artists helps with early sharing and feedback. Use them alongside, not instead of, the main streaming platforms."),
  ("How do I get my music on iTunes, Amazon Music, and Resso in India?",
   "All three are covered by a standard distributor delivery, you do not submit to each separately. Pick a distributor and select the stores, and your release appears on Apple and iTunes, Amazon Music, and other partners automatically."),
 ],
 "guides/how-record-labels-sign-artists-india/index.html": [
  ("How do labels find and sign artists?",
   "Labels watch for traction, streams, live draw, social momentum, then approach, or they field demos. They sign artists who already show a rising audience, not raw potential."),
  ("Should I sign to a record label?",
   'Sign only if the deal adds more than you could do alone and does not take rights you will regret losing. Many Indian artists do better staying independent and keeping their masters, see <a href="/guides/how-to-become-an-independent-artist-india/">becoming an independent artist</a>.'),
  ("What is a 360 deal, and how do record deals work in India?",
   "A 360 deal gives the label a cut of not just recordings but touring, merch, and other income. Standard deals advance money against future royalties; read exactly what rights and revenue streams you are signing away before agreeing."),
  ("How do I approach a record label or submit a demo in India?",
   "Do not cold-blast. Build traction first, then approach through a warm intro or a specific A&R contact with a short, strong link and your numbers. A tight demo plus proof of an audience beats a long email."),
 ],
 "guides/electronic-press-kit-epk-india/index.html": [
  ("What is an EPK for musicians?",
   "An EPK, or electronic press kit, is a single web page or PDF with your bio, photos, best track or video, key stats, press quotes, and contact. Venues, curators, and press use it to decide quickly."),
  ("Is there a free EPK or one-sheet template I can use?",
   "Yes. You can build a free EPK on a simple site or a one-page document, a Linktree, a Notion page, or a Google Doc all work. Keep it to one screen: who you are, your sound, proof, links, and contact."),
  ("What do good EPK examples and artist bios look like?",
   "Strong EPKs lead with the music and one sharp line about who you are, then proof: numbers, press, notable shows. A good artist bio is short, specific, and in third person, one paragraph, not a life story."),
 ],
 "tools/royalty-calculator/index.html": [
  ("How much does Spotify pay per stream, and how do I check my royalties?",
   "Spotify pays roughly 0.10 to 0.30 rupees per stream in India depending on listener geography; check exact earnings in Spotify for Artists or your distributor dashboard. Use the calculator above to estimate before payout."),
  ("When does Spotify pay artists, and what is the payout threshold in India?",
   "Streaming royalties flow through your distributor, which pays out monthly or quarterly once you cross its minimum threshold, often a few hundred to a few thousand rupees. Spotify pays the distributor, and the distributor pays you."),
  ("How do I withdraw my Spotify money in India, and is there GST on royalties?",
   "Withdraw via your distributor to a linked bank account or PayPal once you hit the threshold. Music royalties can attract GST depending on your registration status, so keep records and consult a CA once earnings are significant."),
  ("Is there a Spotify Wrapped for artists?",
   "Yes. Spotify for Artists gives you a year-end and always-on stats dashboard, streams, listeners, top cities, and playlist adds, which is the artist-side equivalent of Wrapped."),
 ],
 "reviewers/index.html": [
  ("What are the best SubmitHub alternatives in India?",
   "Groover and direct pitching are the main alternatives; the database above lists curators, blogs, and playlist editors you can approach directly, many of them for free."),
  ("How do I get my music reviewed in India?",
   "Send a short pitch and a private link to blogs and curators who cover your genre, two to three weeks before release. Filter this database for Indian and South-Asian reviewers to start."),
  ("How do I find music bloggers and do outreach in India?",
   "Use this database to find bloggers by category and cost, then reach out with a tailored one-line pitch and the song. Personal, genre-matched outreach gets replies; mass emails do not."),
  ("Paid vs free music promotion in India: what is worth it?",
   "Free routes, direct pitching, the curators here, and organic short video, should come first. Pay only for legitimate services that reach real curators, never for guaranteed streams or followers."),
 ],
 "guides/build-fanbase-1000-true-fans-india/index.html": [
  ("How do I grow my music audience and get my first 1000 fans in India?",
   "Convert listeners into people you can reach directly, email, WhatsApp, a follow, and give them reasons to stay: consistent releases, behind-the-scenes, live shows. The first 1,000 real fans come from depth, not viral reach."),
  ("What is the 1000 true fans theory, and how do I build a superfan base?",
   "The theory is that around 1,000 fans who each spend a little every year can sustain a career. You build superfans by rewarding your most engaged listeners with early access, merch, and direct access, so casual fans become committed ones."),
  ("How do I keep music fans engaged?",
   "Show up consistently between releases, reply to people, and give them a reason to belong. Engagement is a habit you maintain, not a campaign you run once."),
 ],
 "guides/sync-licensing-music-ads-film-india/index.html": [
  ("What are sync deals, and how are they different from royalty-free music?",
   "A sync deal licenses your specific song for a specific visual, an ad, film, or show, for a negotiated fee. Royalty-free libraries sell generic tracks cheaply for any use; a sync places your actual song and usually pays far more."),
  ("How do I license a song for a YouTube video or for brands in India?",
   "Brands and creators license music directly from the rights holders, you, or your publisher or label, for a fee and a defined usage. Have a clean split sheet ready and be prepared to grant the recording and composition rights together."),
 ],
 "guides/isrc-code-india/index.html": [
  ("What is a UPC code for music, and how is it different from an ISRC?",
   "A UPC identifies a whole release, a single, EP, or album, for sales and distribution; an ISRC identifies each individual recording within it. Your distributor issues both, usually for free."),
 ],
 "guides/make-money-independent-artist-india/index.html": [
  ("What are the main ways to make money from music in India?",
   "Live shows, sync licensing, merch, direct fan support, and publishing royalties via IPRS typically out-earn streaming for independent Indian artists. Build several income streams rather than relying on one."),
 ],
 "guides/12-week-release-plan-india/index.html": [
  ("What is a good single release strategy and rollout plan in India?",
   "Work backwards from the release date over about twelve weeks: assets and distribution first, then playlist and press pitching, then teasers and content, then the release-day push and post-release momentum. A rollout beats a single-day drop."),
 ],
 "guides/free-music-distribution-india/index.html": [
  ("How do I distribute music for free in India?",
   'Use a free-tier distributor that puts you on Spotify and other platforms at no upfront cost in exchange for a revenue share. See our <a href="/guides/best-music-distributor-india/">distributor comparison</a> for which free options are worth it.'),
 ],
}
