#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""deepen_guides.py — inject cluster-gap FAQ Q&As into guides (content + schema).

For each page in deepen_content.DEEPEN it adds the new Q&As to the visible
"People also ask" section (creating the section if the page lacks one) AND to the
page's FAQPage JSON-LD (creating that block if absent), so each answer is both
readable and eligible for a Google FAQ rich result. Idempotent: a Q&A already on
the page is skipped, so re-running after edits is safe.

Run order note: guides are NOT regenerated by the daily Actions pipeline, so these
injections persist. If you ever re-run build_guides.py (adds/rebuilds generated
guides), re-run normalize_guide_ctas.py then this, to reapply both passes.
"""
import re, json, html as htmllib
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from deepen_content import DEEPEN

REPO = Path(__file__).resolve().parent.parent

H3 = '<h3 style="font-size:17px;font-weight:800;margin:20px 0 6px">{q}</h3><p>{a}</p>'
CTA_ANCHORS = ['<div class="g-cta">', '<div class="g-softcta">', '<div class="rc-cta">']

def strip_tags(h):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", h)).replace("&amp;", "&").strip()

def add_to_section(html, items):
    """Append h3/p blocks before the close of the #related section, or build one."""
    add = "\n".join(H3.format(q=htmllib.escape(q), a=a) for q, a in items)
    m = re.search(r'(<section id="related".*?)(</section>)', html, re.S)
    if m:
        return html[:m.start(2)] + add + "\n" + html[m.start(2):]
    # No FAQ section yet: create one just before the CTA (or footer as fallback).
    section = ('  <section id="related" style="margin-top:36px">\n'
               '    <h2>People also ask</h2>\n' + add + '\n  </section>\n')
    for anchor in CTA_ANCHORS:
        i = html.find(anchor)
        if i != -1:
            # step back to the start of that div's line/indentation
            ls = html.rfind("\n", 0, i) + 1
            return html[:ls] + section + html[ls:]
    i = html.rfind("<footer")
    ls = html.rfind("\n", 0, i) + 1
    return html[:ls] + section + html[ls:]

def add_to_jsonld(html, items):
    """Append Questions to the FAQPage JSON-LD, or insert a fresh FAQPage block."""
    new_q = [{"@type": "Question", "name": q,
              "acceptedAnswer": {"@type": "Answer", "text": strip_tags(a)}} for q, a in items]
    for m in re.finditer(r'<script type="application/ld\+json">(.*?)</script>', html, re.S):
        try:
            data = json.loads(m.group(1))
        except Exception:
            continue
        if isinstance(data, dict) and data.get("@type") == "FAQPage":
            data.setdefault("mainEntity", []).extend(new_q)
            block = '<script type="application/ld+json">' + json.dumps(data, ensure_ascii=False) + '</script>'
            return html[:m.start()] + block + html[m.end():]
    data = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": new_q}
    block = '  <script type="application/ld+json">' + json.dumps(data, ensure_ascii=False) + '</script>\n'
    i = html.find("</head>")
    return html[:i] + block + html[i:]

def process(rel, items):
    f = REPO / rel
    if not f.exists():
        return rel, "MISSING FILE"
    html = f.read_text()
    fresh = [(q, a) for q, a in items if q not in html]
    if not fresh:
        return rel, "up-to-date"
    html = add_to_section(html, fresh)
    html = add_to_jsonld(html, fresh)
    f.write_text(html)
    return rel, f"+{len(fresh)} Q&A"

def main():
    added = 0
    for rel, items in DEEPEN.items():
        r, status = process(rel, items)
        print(f"  {status:14} {r}")
        if status.startswith("+"):
            added += int(status[1:].split()[0])
    print(f"deepen_guides: {added} new Q&As injected across {len(DEEPEN)} pages.")

if __name__ == "__main__":
    main()
